"""Web 研究和报告运行时使用的提示词注册表。"""

from deepresearch_agent.config.prompts.reasoning_prompts import (
    FOLLOWUP_QUERY_PROMPT,
    SEARCH_MULTI_HYPOTHESIS_PROMPT,
    SUB_QUERY_PROMPT,
)
from deepresearch_agent.config.prompts.planner_prompts import (
    CLARIFY_PROMPT,
    PLAN_REVIEW_PROMPT,
    TASK_DECOMPOSE_PROMPT,
)
from deepresearch_agent.config.prompts.reporter_prompts import (
    CITATION_FORMAT_PROMPT,
    CONCLUSION_PROMPT,
    CONSISTENCY_CHECK_PROMPT,
    EVIDENCE_MAP_PROMPT,
    INTERMEDIATE_SUMMARY_PROMPT,
    INTRO_PROMPT,
    MERGE_PROMPT,
    OUTLINE_PROMPT,
    OUTLINE_SYSTEM_PROMPT,
    REFINE_PROMPT,
    SECTION_REDUCE_PROMPT,
    SECTION_REDUCE_SYSTEM_PROMPT,
    SECTION_WRITE_PROMPT,
    SECTION_WRITE_SYSTEM_PROMPT,
    TERMINOLOGY_PROMPT,
)

__all__ = [
    "SUB_QUERY_PROMPT",
    "FOLLOWUP_QUERY_PROMPT",
    "SEARCH_MULTI_HYPOTHESIS_PROMPT",
    "TASK_DECOMPOSE_PROMPT",
    "CLARIFY_PROMPT",
    "PLAN_REVIEW_PROMPT",
    "OUTLINE_SYSTEM_PROMPT",
    "OUTLINE_PROMPT",
    "SECTION_WRITE_SYSTEM_PROMPT",
    "SECTION_WRITE_PROMPT",
    "CONSISTENCY_CHECK_PROMPT",
    "CITATION_FORMAT_PROMPT",
    "EVIDENCE_MAP_PROMPT",
    "SECTION_REDUCE_SYSTEM_PROMPT",
    "SECTION_REDUCE_PROMPT",
    "INTERMEDIATE_SUMMARY_PROMPT",
    "MERGE_PROMPT",
    "REFINE_PROMPT",
    "INTRO_PROMPT",
    "CONCLUSION_PROMPT",
    "TERMINOLOGY_PROMPT",
]
